services:
  ml_engine:
    build: ./ml_engine
    volumes:
      - ./ml_engine/models:/app/models
    ports:
      - "127.0.0.1:8001:8001"
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - ML_ENGINE_URL=http://ml_engine:8001
    env_file: ./backend/.env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - ml_engine
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/sortex
      args:
        NEXT_PUBLIC_API_URL: http://13.235.118.152
        NEXT_PUBLIC_API_BASE_URL: http://13.235.118.152
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
